services:
  workspace:
    build:
      context: ..
      dockerfile: docker/workspace/Dockerfile
    runtime: sysbox-runc
    security_opt:
      - seccomp=unconfined
    shm_size: "2gb"
    ports:
      - "5901:5901"
      - "6901:6901"
      - "8000:3000"
    environment:
      - TZ=Europe/Prague
    hostname: workspace.lemongrass.local
    restart: unless-stopped
